---

- name: docker start
  service:
    name: docker
    state: started

- name: docker stop
  service:
    name: docker
    state: stopped

- name: docker restart
  service:
    name: docker
    state: restarted
